export const UNABLE_TO_PARSE_PRICE_ERROR_CODE = 999
export const UNFOUND_PAIR_ERROR_CODE = 400
export const ENDPOINT_DOES_NOT_EXIST_ERROR_CODE = 404
export const UNABLE_TO_REACH_SERVER_ERROR_CODE = 500